apiVersion: v1
data:
  token: Z2hwX2tQdUsxekp6RjBTT2tIQUFadTBycHZDNzJaWGlNNzJtbVdnRg==
  user: ZGlwcHktYm90
kind: Secret
metadata:
  creationTimestamp: "2021-08-18T19:35:48Z"
  name: dippy-bot
  resourceVersion: "14052"
  uid: 1154fa59-5a70-4a21-b38c-d8df9133eb03
type: Opaque
