apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: insights-inventory
  name: insights-inventory
spec:
  ports:
  - name: port-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    # app: host-inventory-service
    app: insights-inventory
    service: insights-inventory
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
