apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: inventory-db
  name: inventory-db
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: inventory-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
