apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-mq
    pod: host-inventory-mq-pmin
  name: inventory-mq-pmin
spec:
  ports:
  - name: port-9126
    port: 9126
    protocol: TCP
    targetPort: 9126
  selector:
    pod: inventory-mq-pmin
  sessionAffinity: None
  type: ClusterIP
