apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: insights-inventory
    pod: host-inventory-synchronizer
  name: host-inventory-synchronizer
spec:
  backoffLimit: 6
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: insights-inventory
        pod: host-inventory-synchronizer
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: insights-inventory
                  pod: host-inventory-synchronizer
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: insights-inventory
                  pod: host-inventory-synchronizer
              topologyKey: kubernetes.io/hostname
            weight: 99
      containers:
        - command:
            - python
            - host_synchronizer.py
          env:
            - name: INVENTORY_DB_HOST
              value: inventory-db.hbi.svc.cluster.local
            - name: INVENTORY_DB_USER
              value: insights
            - name: INVENTORY_DB_PASS
              value: insights
            - name: INVENTORY_DB_NAME
              value: insights
            - name: INVENTORY_DB_PORT
              value: "5432"
            - name: INVENTORY_LOG_LEVEL
              value: DEBUG
            - name: INVENTORY_DB_SSL_MODE
              value: prefer
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: PAYLOAD_TRACKER_KAFKA_TOPIC
              value: platform.payload-status
            - name: PAYLOAD_TRACKER_SERVICE_NAME
              value: inventory-mq-service
            - name: PAYLOAD_TRACKER_ENABLED
              value: "true"
            - name: PROMETHEUS_PUSHGATEWAY
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9091
            - name: KAFKA_PRODUCER_ACKS
              value: "1"
            - name: KAFKA_PRODUCER_RETRIES
              value: "8"
            - name: KAFKA_PRODUCER_RETRY_BACKOFF_MS
              value: "250"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KAFKA_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_SASL_MECHANISM
              value: PLAIN
          image: quay.io/thearifismail/insights-inventory:97d21ce
          imagePullPolicy: IfNotPresent
          name: host-inventory-synchronizer
          ports:
            - containerPort: 9126
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
