apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-mq
  name: inventory-mq
spec:
  ports:
  - name: port-9126
    port: 9126
    protocol: TCP
    targetPort: 9126
  selector:
    app: inventory-mq
  sessionAffinity: None
  type: ClusterIP
