apiVersion: v1
kind: Template
metadata:
  name: insights-inventory-db
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: inventory-db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: inventory-db
    name: inventory-db
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{DB_REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        name: inventory-db
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: inventory-db
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: name
                    operator: In
                    values:
                    - inventory-db
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: name
                    operator: In
                    values:
                    - inventory-db
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: host-inventory-db
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: host-inventory-db
          - name: POSTGRESQL_DATABASE
            value: insights
          image: registry.access.redhat.com/rhscl/postgresql-95-rhel7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - pg_isready -h 127.0.0.1 -p 5432
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
          name: inventory-db
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: inventory-db-data
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - pg_ctl stop -D /var/lib/pgsql/data/userdata
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: inventory-db-data
          persistentVolumeClaim:
            claimName: inventory-db
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    creationTimestamp: null
    labels:
      app: inventory-db
    name: inventory-db
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: inventory-db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: Size for volumes
  name: VOLUME_CAPACITY
  value: 5Gi
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: How many pod replicas for the db
  name: DB_REPLICAS
  value: '0'
